dataSources:
  - name: bds
    type: csv
    config:
      path: "data/bds2018.csv"
  - name: bds_cty
    type: csv
    config:
      path: "data/bds2018_cty.csv"
  - name: bds_eag
    type: csv
    config:
      path: "data/bds2018_eage.csv"
  - name: bds_esize
    type: csv
    config:
      path: "data/bds2018_esize.csv"
  - name: bds_fage
    type: csv
    config:
      path: "data/bds2018_fage.csv"
  - name: bds_fsize
    type: csv
    config:
      path: "data/bds2018_fsize.csv"
  - name: bds_iesize
    type: csv
    config:
      path: "data/bds2018_iesize.csv"
  - name: bds_ifsize
    type: csv
    config:
      path: "data/bds2018_ifsize.csv"
  - name: bds_metro
    type: csv
    config:
      path: "data/bds2018_metro.csv"
  - name: bds_msa
    type: csv
    config:
      path: "data/bds2018_msa.csv"
  - name: bds_sector
    type: csv
    config:
      path: "data/bds2018_sector.csv"
  - name: bds_st
    type: csv
    config:
      path: "data/bds2018_st.csv"
  - name: bds_vcnaics3
    type: csv
    config:
      path: "data/bds2018_vcnaics3.csv"
  - name: bds_vcnaics4
    type: csv
    config:
      path: "data/bds2018_vcnaics4.csv"
  - name: geo
    type: csv
    config:
      path: "data/geo.csv"
