services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ../sql/init:/docker-entrypoint-initdb.d

  rest:
    image: oletizi/nlsearch-rest-api
    ports:
      - 3000:3000
