USE bds;

CREATE TABLE bds2018 (
	year DECIMAL(38, 0) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 3) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 3) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births DECIMAL(38, 3) NOT NULL,
	job_creation_rate DECIMAL(38, 3) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths DECIMAL(38, 0) NOT NULL,
	job_destruction_continuers DECIMAL(38, 0) NOT NULL,
	job_destruction_rate_deaths DECIMAL(38, 3) NOT NULL,
	job_destruction_rate DECIMAL(38, 3) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 3) NOT NULL,
	reallocation_rate DECIMAL(38, 3) NOT NULL,
	firmdeath_firms DECIMAL(38, 0) NOT NULL,
	firmdeath_estabs DECIMAL(38, 0) NOT NULL,
	firmdeath_emp DECIMAL(38, 0) NOT NULL
);
CREATE TABLE bds2018_cty (
	year DECIMAL(38, 0) NOT NULL,
	st DECIMAL(38, 0) NOT NULL,
	cty DECIMAL(38, 0) NOT NULL,
	firms VARCHAR(6) NOT NULL,
	estabs VARCHAR(6) NOT NULL,
	emp VARCHAR(7) NOT NULL,
	denom VARCHAR(7) NOT NULL,
	estabs_entry VARCHAR(5) NOT NULL,
	estabs_entry_rate VARCHAR(7),
	estabs_exit VARCHAR(5) NOT NULL,
	estabs_exit_rate VARCHAR(7),
	job_creation VARCHAR(6) NOT NULL,
	job_creation_births VARCHAR(6) NOT NULL,
	job_creation_continuers VARCHAR(6) NOT NULL,
	job_creation_rate_births VARCHAR(7),
	job_creation_rate VARCHAR(7),
	job_destruction VARCHAR(6) NOT NULL,
	job_destruction_deaths VARCHAR(6) NOT NULL,
	job_destruction_continuers VARCHAR(6) NOT NULL,
	job_destruction_rate_deaths VARCHAR(7),
	job_destruction_rate VARCHAR(7),
	net_job_creation VARCHAR(7) NOT NULL,
	net_job_creation_rate VARCHAR(8),
	reallocation_rate VARCHAR(7),
	firmdeath_firms VARCHAR(5) NOT NULL,
	firmdeath_estabs VARCHAR(5) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
CREATE TABLE bds2018_eage (
	year DECIMAL(38, 0) NOT NULL,
	eage VARCHAR(16) NOT NULL,
	firms VARCHAR(7) NOT NULL,
	estabs VARCHAR(7) NOT NULL,
	emp VARCHAR(8) NOT NULL,
	denom VARCHAR(8) NOT NULL,
	estabs_entry VARCHAR(6) NOT NULL,
	estabs_entry_rate VARCHAR(18),
	estabs_exit VARCHAR(6) NOT NULL,
	estabs_exit_rate VARCHAR(18),
	job_creation VARCHAR(7) NOT NULL,
	job_creation_births VARCHAR(7) NOT NULL,
	job_creation_continuers VARCHAR(7) NOT NULL,
	job_creation_rate_births VARCHAR(7),
	job_creation_rate VARCHAR(7),
	job_destruction VARCHAR(7) NOT NULL,
	job_destruction_deaths VARCHAR(7) NOT NULL,
	job_destruction_continuers DECIMAL(38, 0) NOT NULL,
	job_destruction_rate_deaths VARCHAR(6),
	job_destruction_rate VARCHAR(6),
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 3),
	reallocation_rate VARCHAR(6),
	firmdeath_firms VARCHAR(6) NOT NULL,
	firmdeath_estabs VARCHAR(6) NOT NULL,
	firmdeath_emp VARCHAR(7) NOT NULL
);
CREATE TABLE bds2018_esize (
	year DECIMAL(38, 0) NOT NULL,
	esize VARCHAR(13) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 16) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 16) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births DECIMAL(38, 16) NOT NULL,
	job_creation_rate DECIMAL(38, 16) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths DECIMAL(38, 0) NOT NULL,
	job_destruction_continuers VARCHAR(7) NOT NULL,
	job_destruction_rate_deaths DECIMAL(38, 16) NOT NULL,
	job_destruction_rate DECIMAL(38, 16) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 17) NOT NULL,
	reallocation_rate DECIMAL(38, 15) NOT NULL,
	firmdeath_firms VARCHAR(6) NOT NULL,
	firmdeath_estabs VARCHAR(6) NOT NULL,
	firmdeath_emp VARCHAR(7) NOT NULL
);
CREATE TABLE bds2018_fage (
	year DECIMAL(38, 0) NOT NULL,
	fage VARCHAR(16) NOT NULL,
	firms VARCHAR(7) NOT NULL,
	estabs VARCHAR(7) NOT NULL,
	emp VARCHAR(8) NOT NULL,
	denom VARCHAR(8) NOT NULL,
	estabs_entry VARCHAR(6) NOT NULL,
	estabs_entry_rate VARCHAR(19),
	estabs_exit VARCHAR(6) NOT NULL,
	estabs_exit_rate VARCHAR(18),
	job_creation VARCHAR(8) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers VARCHAR(7) NOT NULL,
	job_creation_rate_births DECIMAL(38, 3),
	job_creation_rate VARCHAR(7),
	job_destruction VARCHAR(7) NOT NULL,
	job_destruction_deaths VARCHAR(7) NOT NULL,
	job_destruction_continuers VARCHAR(7) NOT NULL,
	job_destruction_rate_deaths VARCHAR(6),
	job_destruction_rate VARCHAR(6),
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 3),
	reallocation_rate VARCHAR(6),
	firmdeath_firms VARCHAR(6) NOT NULL,
	firmdeath_estabs VARCHAR(6) NOT NULL,
	firmdeath_emp VARCHAR(7) NOT NULL
);
CREATE TABLE bds2018_fsize (
	year DECIMAL(38, 0) NOT NULL,
	fsize VARCHAR(15) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 16) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 16) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births DECIMAL(38, 16) NOT NULL,
	job_creation_rate DECIMAL(38, 15) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths DECIMAL(38, 0) NOT NULL,
	job_destruction_continuers DECIMAL(38, 0) NOT NULL,
	job_destruction_rate_deaths DECIMAL(38, 16) NOT NULL,
	job_destruction_rate DECIMAL(38, 15) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 18) NOT NULL,
	reallocation_rate DECIMAL(38, 15) NOT NULL,
	firmdeath_firms VARCHAR(6) NOT NULL,
	firmdeath_estabs VARCHAR(6) NOT NULL,
	firmdeath_emp VARCHAR(7) NOT NULL
);
CREATE TABLE bds2018_iesize (
	year DECIMAL(38, 0) NOT NULL,
	iesize VARCHAR(13) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 16) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 16) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births DECIMAL(38, 16) NOT NULL,
	job_creation_rate DECIMAL(38, 16) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths DECIMAL(38, 0) NOT NULL,
	job_destruction_continuers VARCHAR(7) NOT NULL,
	job_destruction_rate_deaths DECIMAL(38, 16) NOT NULL,
	job_destruction_rate DECIMAL(38, 16) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 17) NOT NULL,
	reallocation_rate DECIMAL(38, 15) NOT NULL,
	firmdeath_firms DECIMAL(38, 0) NOT NULL,
	firmdeath_estabs DECIMAL(38, 0) NOT NULL,
	firmdeath_emp DECIMAL(38, 0) NOT NULL
);
CREATE TABLE bds2018_ifsize (
	year DECIMAL(38, 0) NOT NULL,
	ifsize VARCHAR(15) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 16) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 16) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births DECIMAL(38, 16) NOT NULL,
	job_creation_rate DECIMAL(38, 15) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths DECIMAL(38, 0) NOT NULL,
	job_destruction_continuers DECIMAL(38, 0) NOT NULL,
	job_destruction_rate_deaths DECIMAL(38, 16) NOT NULL,
	job_destruction_rate DECIMAL(38, 15) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 18) NOT NULL,
	reallocation_rate DECIMAL(38, 15) NOT NULL,
	firmdeath_firms VARCHAR(6) NOT NULL,
	firmdeath_estabs VARCHAR(6) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
CREATE TABLE bds2018_metro (
	year DECIMAL(38, 0) NOT NULL,
	metro VARCHAR(2) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 3) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 3) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births DECIMAL(38, 3) NOT NULL,
	job_creation_rate DECIMAL(38, 3) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths DECIMAL(38, 0) NOT NULL,
	job_destruction_continuers DECIMAL(38, 0) NOT NULL,
	job_destruction_rate_deaths DECIMAL(38, 3) NOT NULL,
	job_destruction_rate DECIMAL(38, 3) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 3) NOT NULL,
	reallocation_rate DECIMAL(38, 3) NOT NULL,
	firmdeath_firms DECIMAL(38, 0) NOT NULL,
	firmdeath_estabs DECIMAL(38, 0) NOT NULL,
	firmdeath_emp DECIMAL(38, 0) NOT NULL
);
CREATE TABLE bds2018_msa (
	year DECIMAL(38, 0) NOT NULL,
	msa DECIMAL(38, 0) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp VARCHAR(7) NOT NULL,
	denom VARCHAR(7) NOT NULL,
	estabs_entry VARCHAR(5) NOT NULL,
	estabs_entry_rate VARCHAR(18) NOT NULL,
	estabs_exit VARCHAR(5) NOT NULL,
	estabs_exit_rate VARCHAR(18) NOT NULL,
	job_creation VARCHAR(7) NOT NULL,
	job_creation_births VARCHAR(6) NOT NULL,
	job_creation_continuers VARCHAR(6) NOT NULL,
	job_creation_rate_births VARCHAR(19) NOT NULL,
	job_creation_rate VARCHAR(18) NOT NULL,
	job_destruction VARCHAR(7) NOT NULL,
	job_destruction_deaths VARCHAR(6) NOT NULL,
	job_destruction_continuers VARCHAR(6) NOT NULL,
	job_destruction_rate_deaths VARCHAR(18) NOT NULL,
	job_destruction_rate VARCHAR(18) NOT NULL,
	net_job_creation VARCHAR(7) NOT NULL,
	net_job_creation_rate VARCHAR(21) NOT NULL,
	reallocation_rate VARCHAR(18) NOT NULL,
	firmdeath_firms VARCHAR(5) NOT NULL,
	firmdeath_estabs VARCHAR(5) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
CREATE TABLE bds2018_sector (
	year DECIMAL(38, 0) NOT NULL,
	sector VARCHAR(5) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 16) NOT NULL,
	estabs_exit DECIMAL(38, 0) NOT NULL,
	estabs_exit_rate DECIMAL(38, 16) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births DECIMAL(38, 0) NOT NULL,
	job_creation_continuers VARCHAR(7) NOT NULL,
	job_creation_rate_births DECIMAL(38, 16) NOT NULL,
	job_creation_rate DECIMAL(38, 16) NOT NULL,
	job_destruction VARCHAR(7) NOT NULL,
	job_destruction_deaths VARCHAR(6) NOT NULL,
	job_destruction_continuers VARCHAR(7) NOT NULL,
	job_destruction_rate_deaths VARCHAR(20) NOT NULL,
	job_destruction_rate VARCHAR(18) NOT NULL,
	net_job_creation VARCHAR(8) NOT NULL,
	net_job_creation_rate DECIMAL(38, 18) NOT NULL,
	reallocation_rate VARCHAR(18) NOT NULL,
	firmdeath_firms VARCHAR(5) NOT NULL,
	firmdeath_estabs VARCHAR(5) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
CREATE TABLE bds2018_st (
	year DECIMAL(38, 0) NOT NULL,
	st DECIMAL(38, 0) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry DECIMAL(38, 0) NOT NULL,
	estabs_entry_rate DECIMAL(38, 16) NOT NULL,
	estabs_exit VARCHAR(5) NOT NULL,
	estabs_exit_rate VARCHAR(6) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births VARCHAR(6) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births VARCHAR(18) NOT NULL,
	job_creation_rate DECIMAL(38, 15) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths VARCHAR(6) NOT NULL,
	job_destruction_continuers VARCHAR(7) NOT NULL,
	job_destruction_rate_deaths VARCHAR(6) NOT NULL,
	job_destruction_rate DECIMAL(38, 16) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 18) NOT NULL,
	reallocation_rate DECIMAL(38, 15) NOT NULL,
	firmdeath_firms VARCHAR(5) NOT NULL,
	firmdeath_estabs VARCHAR(5) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
CREATE TABLE bds2018_vcnaics3 (
	year DECIMAL(38, 0) NOT NULL,
	vcnaics3 DECIMAL(38, 0) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry VARCHAR(6) NOT NULL,
	estabs_entry_rate VARCHAR(6) NOT NULL,
	estabs_exit VARCHAR(5) NOT NULL,
	estabs_exit_rate VARCHAR(6) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births VARCHAR(6) NOT NULL,
	job_creation_continuers DECIMAL(38, 0) NOT NULL,
	job_creation_rate_births VARCHAR(7) NOT NULL,
	job_creation_rate DECIMAL(38, 3) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths VARCHAR(6) NOT NULL,
	job_destruction_continuers DECIMAL(38, 0) NOT NULL,
	job_destruction_rate_deaths VARCHAR(6) NOT NULL,
	job_destruction_rate DECIMAL(38, 3) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 3) NOT NULL,
	reallocation_rate DECIMAL(38, 3) NOT NULL,
	firmdeath_firms VARCHAR(5) NOT NULL,
	firmdeath_estabs VARCHAR(5) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
CREATE TABLE bds2018_vcnaics4 (
	year DECIMAL(38, 0) NOT NULL,
	vcnaics4 DECIMAL(38, 0) NOT NULL,
	firms DECIMAL(38, 0) NOT NULL,
	estabs DECIMAL(38, 0) NOT NULL,
	emp DECIMAL(38, 0) NOT NULL,
	denom DECIMAL(38, 0) NOT NULL,
	estabs_entry VARCHAR(5) NOT NULL,
	estabs_entry_rate VARCHAR(6) NOT NULL,
	estabs_exit VARCHAR(5) NOT NULL,
	estabs_exit_rate VARCHAR(7) NOT NULL,
	job_creation DECIMAL(38, 0) NOT NULL,
	job_creation_births VARCHAR(6) NOT NULL,
	job_creation_continuers VARCHAR(6) NOT NULL,
	job_creation_rate_births VARCHAR(7) NOT NULL,
	job_creation_rate DECIMAL(38, 3) NOT NULL,
	job_destruction DECIMAL(38, 0) NOT NULL,
	job_destruction_deaths VARCHAR(6) NOT NULL,
	job_destruction_continuers VARCHAR(7) NOT NULL,
	job_destruction_rate_deaths VARCHAR(7) NOT NULL,
	job_destruction_rate DECIMAL(38, 3) NOT NULL,
	net_job_creation DECIMAL(38, 0) NOT NULL,
	net_job_creation_rate DECIMAL(38, 3) NOT NULL,
	reallocation_rate DECIMAL(38, 3) NOT NULL,
	firmdeath_firms VARCHAR(5) NOT NULL,
	firmdeath_estabs VARCHAR(5) NOT NULL,
	firmdeath_emp VARCHAR(6) NOT NULL
);
